### ISSUE TITLE
Update the readme to make it easy for people to use this plugin

### ISSUE THREAD

**Issue by adrianbrink** [adrianbrink/spiegelplus-decryptor#1]
It would be great to update the readme so that newbies can follow easy instructions to set it up with tampermonkey in Chrome.

**Comment by sanchit-bansal** [comment]
I will do it. 

Please assign it to me

**Comment by adrianbrink** [comment]
Thanks :-) 

How can I assign this issue to you? Do I need to add you as a collaborator?

**Comment by sanchit-bansal** [comment]
Done. Check fast :) https://github.com/adrianbrink/spiegelplus-decryptor/pull/2/commits/8b29d2d2306ca09f2ae7f37c232d2825f9349f98
